### ISSUE TITLE
Cover "tilt" is not available

### ISSUE THREAD

**Issue by KrisDeWilde** [thomasddn/qbha#10]
**Describe the bug**
I have 4 vertical blinds in my home, they can open or close completely, but you can also tilt them so you can look outside. 
Everything works via Qbus and can be controlled in the Qbus app on Android. 

In home-assistant, the mqtt messages arrive correctly, but the translation from mqtt to a cover entity does not proceed correctly. 
I suspect that "slatposition" from mqtt does not translate to "tilt-position" in the cover entity. 
Except when the fault is my own, of course. (I'm not a programmer)

**To Reproduce**
A little snap of mqtt logs:

Qbus Lamellen achterdeur (cover.qbus_ul1_156)
MQTT discovery data:
	•	Topic: homeassistant/cover/qbus_UL1_156/config
	•	Payload
Subscribed topics:
	•	cloudapp/QBUSMQTTGW/UL1/UL31/state
			10 meest recent ontvangen bericht(en)
				-Received 08:30:05
					QoS:  @0
					Payload: 
					id: UL31
					properties:
					  slatPosition: 50
					type: event
				-Received 13:07:57
					QoS: 0
					Payload: 
					id: UL31
					properties:
					  shutterPosition: 100
					type: event

**Expected behavior**
When slatposition is found in mqtt, create a cover entitie with a "cover tilt position"
When shutterposition is found in mqtt, create a cover entitie with "cover position"

**QBHA version and installation type:**
Huidige versie: 0.8.0
HA add-on

**Qbus MQTT version and installation type:**
Huidige versie: 0.4.0
HA add-on

**Home Assistant:**
Installation type: HAOS/Generic x86-64
Version: 
Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2

**Comment by thomasddn** [comment]
Hi @KrisDeWilde, a new version has been released with support for tilt!
