### ISSUE TITLE
QBHA stops after updating to 0.7

### ISSUE THREAD

**Issue by LennartMart** [thomasddn/qbha#6]
**Describe the bug**
After updating to 0.7 and restarting the Gateway, the logs were filled with
`expected string, tuple found`.  LuQas entities were created succesfully, but QBHA keeps stopping now.

**To Reproduce**
1. Update QBHA to 0.7
2. Restart Gateway
3. ... and have LuQas :-)

**Expected behavior**
QBHA running. After restart, these errors happen:(removed some devices.0.functionBlocks.{number}.variant errors, since they are the same)..

`devices.0.functionBlocks.104.variant
  Input should be a valid string [type=string_type, input_value=[None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
devices.0.functionBlocks.105.variant
  Input should be a valid string [type=string_type, input_value=[None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
devices.0.functionBlocks.107.variant
  Input should be a valid string [type=string_type, input_value=[None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
devices.0.functionBlocks.108.variant
  Input should be a valid string [type=string_type, input_value=[None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
devices.0.functionBlocks.109.variant
  Input should be a valid string [type=string_type, input_value=[None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started`

**QBHA version:**
v0.7.0

**Qbus MQTT version:**
docker v0.1.0 / bare metal

**Home Assistant:**
Installation type: HAOS (HA Yellow)
Version: 2024.05.05

**Comment by thomasddn** [comment]
Could you attach your qbusconfig.json file? It should be in the _share_ folder. Replace all occurences of your controller id (about 6 numbers long).

You can also send it privately via the qbus forum if you like.

**Comment by LennartMart** [comment]
Gladly, but I don't see how... Any tips on how to get to the _share folder?

**Comment by thomasddn** [comment]
I think I was able to fix it based on someone else's qbusconfig.json file. Could you try v0.7.1 and let me know?

> Any tips on how to get to the _share folder?

If you're on HAOS, the easiest is to install the `Samba share` addon. Once installed and configured, you can access some directories on the HAOS machine by opening `\\ip.of.your.haos`. Find the `addon_configs` folder (and not the `share` folder as I stated earlier) and navigate to the QBHA folder in which you should find the file.

**Comment by thomasddn** [comment]
A variant defines what type of gauge (sensor) it is, e.g. power, energy, current, voltage, water, temperature. But sometimes this variant is a list with an empty value in it (instead of just text) and that was giving errors.

**Comment by mathiasbl** [comment]
I'm thinking if we should add the min, max and step to the mqtt config. This would allow you to add gauge card in HA. What do you think?

**Comment by thomasddn** [comment]
@mathiasbl Unless I'm overlooking something, I don't think there is such a thing as min, max and step in the sensor mqtt config: https://www.home-assistant.io/integrations/sensor.mqtt. You should be able to use the sensors in a gauge card, regardless of any preconfigured min/max values, but you need to enter those values manually while configuring the gauge card.

**Comment by BertBJ40** [comment]
After updating to 0.7.2 and restarting the Gateway, the logs were filled with
expected string, tuple found. I don't have LuQas. But QBHA keeps stopping now.

[21:32:35] INFO: Retrieving MQTT settings from MQTT addon.
2024-08-29 21:32:37,575 qbha INFO - Starting QBHA v0.7.2.
2024-08-29 21:32:37,581 qbha.Qbha INFO - MQTT client connecting to core-mosquitto:1883 with user 'addons'.
2024-08-29 21:33:58,625 qbha.Subscribers.QbusControllerStateSubscriber INFO - Activating controller UL1.
2024-08-29 21:34:36,882 qbha.Subscribers.QbusConfigSubscriber INFO - New Qbus config, updating Home Assistant entities.
/usr/local/lib/python3.12/site-packages/pydantic/main.py:352: UserWarning: Pydantic serializer warnings:
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected
  Expected `Union[str, list[any]]` but got `tuple` - serialized value may not be as expected

**Comment by thomasddn** [comment]
Hi @BertBJ40! Can you please upload your qbusconfig.json to this link: https://www.dropbox.com/request/6KptLjqsDcefQnjDJRvU. Uploads are only visible to me.

**Comment by BertBJ40** [comment]
Thomas,
bestand geupload in dropbox
Vriendelijke groeten
Bert Naessens

    Op vrijdag 30 augustus 2024 om 15:37:14 CEST schreef Thomas D ***@***.***>:  
 
 


Hi @BertBJ40! Can you please upload your qbusconfig.json to this link: https://www.dropbox.com/request/6KptLjqsDcefQnjDJRvU. Uploads are only visible to me.

**Comment by thomasddn** [comment]
Version 0.7.3 has been released to fix the warnings. However, I'm not sure if that will solve your problem to be honest. Because, to my surprise, I was seeing the same log messages in my environment and QBHA did not stop working.

Should you still have issues with v0.7.3, please open a new ticket.
