### ISSUE TITLE
Support for CO2 sensor/entity type ventilation?

### ISSUE THREAD

**Issue by SamDeZwam** [thomasddn/qbha#9]
Hi,

Thanks for your work on this, works great.

I'm just missing the ventilation entity type:
From the logs:
2024-09-14 06:57:21,163 qbha.Subscribers.QbusConfigSubscriber WARNING - Entity type 'ventilation' not (yet) supported.

I have the AIR01CT co2 sensor which measures C02 concentration in the living room. The value is used to trigger higher or lower ventilation speeds. At the moment the logic is in the QBUS system, visualisation is with Ubie

It would be nice if I could migrate this to home assistant.

Kind regards,
Sam

![image](https://github.com/user-attachments/assets/8f31db66-988e-45dc-be40-458891335266)

**Comment by thomasddn** [comment]
Hi! Do I understand correctly that you want both the ventilation and the co2 sensor in HA?

Can you upload your qbusconfig.json file to https://www.dropbox.com/request/JwAJj6fzojRBDtiSTEUj? (Only I can see what you upload.) Please also provide the exact names of the entities you want in HA.

How to get the qbusconfig.json file is explained in the faq: https://github.com/thomasddn/qbha/wiki/FAQ

**Comment by SamDeZwam** [comment]
Hi,
Only the CO2 sensor is needed.
I've uploaded the file.
It's this one (other items regarding ventilatie in the file are switches to regulate speed of the ventilation):
{
                    "id": "UL33",
                    "location": "",
                    "locationId": 0,
                    "name": "Luchtsensor",
                    "originalName": "Luchtsensor",
                    "refId": "000494/224",
                    "type": "ventilation",
                    "variant": [
                        null
                    ],
                    "actions": {
                    },
                    "properties": {
                        "co2": {
                            "max": 5000,
                            "min": 0,
                            "read": true,
                            "step": 16,
                            "type": "number",
                            "unit": "ppm",
                            "write": false
                        },
                        "currRegime": {
                            "enumValues": [
                                "Manueel",
                                "Nacht",
                                "Boost",
                                "Uit",
                                "Auto"
                            ],
                            "read": true,
                            "type": "enumString",
                            "write": true
                        },
                        "refresh": {
                            "max": 100,
                            "min": 0,
                            "read": true,
                            "step": 1,
                            "type": "number",
                            "write": true
                        }
                    }
Thanks,
Sam

**Comment by thomasddn** [comment]
I'm trying to create the same output in System Manager, but can't find the exact output to use. Can you share how to create this output in System Manager? Maybe add some screenshots as well.

**Comment by thomasddn** [comment]
I will also need the value from the state topic of that output. Please enable QBUS_CAPTURE and restart QBHA. Then wait until the the sensor changes value. It will log the value to `qbuscapture.log`. Look for `cloudapp/QBUSMQTTGW/UL1/UL33/state`.

Afterwards, disable QBUS_CAPTURE again and restart.

**Comment by SamDeZwam** [comment]
Dag Thomas,

Sorry voor de vertraging, heb na een fietsongeval een weekje doorgebracht
in het ziekenhuis.

System manager:
Eerste screenshot zonder de actuele waarden te lezen

[image: image.png]

Met lezen van actuele waarden:
Voor mij is de CO2 waarde de belangrijkste.

[image: image.png]


Hieronder heb ik geen aanpassingen gedaan, de snelheid wordt adhv logica /
co2 waarde aangestuurd (volgende screenshot)

[image: image.png]

Logica:

[image: image.png]

Ventilatie hoog config:

[image: image.png]


In bijlage de logfile.

Vriendelijke groeten,
Sam



Op vr 20 sep 2024 om 13:32 schreef Thomas D ***@***.***>:

**Comment by thomasddn** [comment]
@SamDeZwam First of all I hope everything is OK!

The images and attachment didn't come through, probably because you answered via email.

**Comment by SamDeZwam** [comment]
Dag Thomas,

Tweede poging ;-)

Schade valt beter mee dan initieel ingeschat, 't is nog voornamelijk herstellen van een hersenschudding.

System manager:
Eerste screenshot zonder de actuele waarden te lezen

![image](https://github.com/user-attachments/assets/9a09f501-330e-459d-9300-ed815199734b)

Met lezen van actuele waarden:
Voor mij is de CO2 waarde de belangrijkste.

![image](https://github.com/user-attachments/assets/992223e9-3b74-4592-aa8d-15379243fa03)


Hieronder heb ik geen aanpassingen gedaan, de snelheid wordt adhv logica /
co2 waarde aangestuurd (volgende screenshot)

![image](https://github.com/user-attachments/assets/6801ca74-7bd4-4b35-b364-5691ce0d6afa)

Logica:

![image](https://github.com/user-attachments/assets/2bfc1e5c-e67d-4621-a86a-f35372271c9f)

Ventilatie hoog config:

![image](https://github.com/user-attachments/assets/73a0f473-13f3-4b74-a5b8-a8ed9106c4dc)


In bijlage de logfile.

Vriendelijke groeten,
Sam

[qbuscapture.log](https://github.com/user-attachments/files/17118105/qbuscapture.log)

**Comment by thomasddn** [comment]
Support has been added in the new release (v0.8.0). Please reopen this issue if something is not working as it should.
